# Generated by Django 2.2.1 on 2019-06-10 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 7, 52, 38, 28411)),
        ),
    ]
