# Generated by Django 2.2.1 on 2019-06-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_articles2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Articles2',
        ),
    ]
